name: Frontend CI

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
    frontend-build:
      runs-on: ubuntu-latest
    
      defaults:
        run:
          working-directory: ./frontend

      steps:
        # 1. Clone the Repository
        - name: Checkout Code
          uses: actions/checkout@v4
        
        # 2. Set up specific Node.js and npm version
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json   
        
        # 3. Install npm dependencies
        - name: Install Dependencies
          run: npm ci
        
        # 4. Check Formatting using Prettier
        - name: Check Formatting (Prettier)
          run: npx prettier --check .
            
        # 5. Check for Potential Bugs
        - name: Run ESLint
          run: npm run lint

        # 5.5 Check React Anti-patterns & Performance (React Doctor)
        - name: Run React Doctor
          run: npx react-doctor@latest

        # 6. Check for Dead Code & Dependencies
        - name: Check Unused Code & Dependencies
          run: npx knip
        
        # 7. Look for Dependency Vulnerabilities
        - name: Audit Dependencies
          run: npx better-npm-audit audit --level high
        
        # TODO Add Automated Testing once Ready
        
        # 8. Perform a Production Build test
        - name: Production Build Test
          run: npm run build
